### ISSUE TITLE
.NET45 Test failing with scoping

### ISSUE THREAD

**Issue by aidapsibr** [psibr/Contextually#6]

**Comment by aidapsibr** [comment]
@tyrotoxin Can you look at this?

**Comment by kind-serge** [comment]
I know what's going on, but haven't figure out how to solve it in a nice way yet..

**Comment by kind-serge** [comment]
I found one way around - to use .NET's `AsyncLocal<T>` with a wrapper when it's not available in .NET 4.5 contract, but available at runtime.

**Comment by aidapsibr** [comment]
@tyrotoxin Can we prioritize getting a fix in-place. I've been asked to resolve the issues or we will have to cut the usage of the 4.5 version.

**Comment by aidapsibr** [comment]
This was reported today again, added test to show the failure in #9

**Comment by aidapsibr** [comment]
Closed by #8
